"use client";
import "./globals.css";

import { Inter } from "next/font/google";
import { CssBaseline, ThemeProvider, createTheme } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const theme = createTheme();

  return (
    <html lang="en">
      <body className={inter.className}>
    {children}
      </body>
    </html>
  );
}
